apiVersion: 1

datasources:
  - name: HD Platform PostgreSQL
    type: postgres
    url: postgres:5432
    user: hduser
    database: hdplatform
    secureJsonData:
      password: hdplatform123
    jsonData:
      sslmode: disable
      postgresVersion: 1300
      timescaledb: false
    access: proxy
    isDefault: true